# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ibai/vivado/ESDC/Lab2/version1_hw/version1_hw.srcs/sources_1/bd/version1_hw/ip/version1_hw_clk_wiz_0_0/version1_hw_clk_wiz_0_0.xci
# IP: The module: 'version1_hw_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ibai/vivado/ESDC/Lab2/version1_hw/version1_hw.srcs/sources_1/bd/version1_hw/ip/version1_hw_clk_wiz_0_0/version1_hw_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'version1_hw_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/ibai/vivado/ESDC/Lab2/version1_hw/version1_hw.srcs/sources_1/bd/version1_hw/ip/version1_hw_clk_wiz_0_0/version1_hw_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'version1_hw_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/ibai/vivado/ESDC/Lab2/version1_hw/version1_hw.srcs/sources_1/bd/version1_hw/ip/version1_hw_clk_wiz_0_0/version1_hw_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'version1_hw_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /home/ibai/vivado/ESDC/Lab2/version1_hw/version1_hw.srcs/sources_1/bd/version1_hw/ip/version1_hw_clk_wiz_0_0/version1_hw_clk_wiz_0_0.xci
# IP: The module: 'version1_hw_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ibai/vivado/ESDC/Lab2/version1_hw/version1_hw.srcs/sources_1/bd/version1_hw/ip/version1_hw_clk_wiz_0_0/version1_hw_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'version1_hw_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/ibai/vivado/ESDC/Lab2/version1_hw/version1_hw.srcs/sources_1/bd/version1_hw/ip/version1_hw_clk_wiz_0_0/version1_hw_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'version1_hw_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/ibai/vivado/ESDC/Lab2/version1_hw/version1_hw.srcs/sources_1/bd/version1_hw/ip/version1_hw_clk_wiz_0_0/version1_hw_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'version1_hw_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
