# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ibai/vivado/ESDC/Lab2/version1_sf/version1_sf.srcs/sources_1/bd/version1_sf/ip/version1_sf_xbar_2/version1_sf_xbar_2.xci
# IP: The module: 'version1_sf_xbar_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ibai/vivado/ESDC/Lab2/version1_sf/version1_sf.srcs/sources_1/bd/version1_sf/ip/version1_sf_xbar_2/version1_sf_xbar_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'version1_sf_xbar_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /home/ibai/vivado/ESDC/Lab2/version1_sf/version1_sf.srcs/sources_1/bd/version1_sf/ip/version1_sf_xbar_2/version1_sf_xbar_2.xci
# IP: The module: 'version1_sf_xbar_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ibai/vivado/ESDC/Lab2/version1_sf/version1_sf.srcs/sources_1/bd/version1_sf/ip/version1_sf_xbar_2/version1_sf_xbar_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'version1_sf_xbar_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
