# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Lab2/zyboVGA_lab2_sw.xdc

# Block Designs: bd/version1_sf/version1_sf.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==version1_sf || ORIG_REF_NAME==version1_sf}]

# IP: bd/version1_sf/ip/version1_sf_axi_gpio_0_0/version1_sf_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==version1_sf_axi_gpio_0_0 || ORIG_REF_NAME==version1_sf_axi_gpio_0_0}]

# IP: bd/version1_sf/ip/version1_sf_axi_gpio_0_1/version1_sf_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==version1_sf_axi_gpio_0_1 || ORIG_REF_NAME==version1_sf_axi_gpio_0_1}]

# IP: bd/version1_sf/ip/version1_sf_axi_gpio_0_2/version1_sf_axi_gpio_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==version1_sf_axi_gpio_0_2 || ORIG_REF_NAME==version1_sf_axi_gpio_0_2}]

# IP: bd/version1_sf/ip/version1_sf_axi_gpio_0_3/version1_sf_axi_gpio_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==version1_sf_axi_gpio_0_3 || ORIG_REF_NAME==version1_sf_axi_gpio_0_3}]

# IP: bd/version1_sf/ip/version1_sf_processing_system7_0_3/version1_sf_processing_system7_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==version1_sf_processing_system7_0_3 || ORIG_REF_NAME==version1_sf_processing_system7_0_3}]

# IP: bd/version1_sf/ip/version1_sf_rst_ps7_0_100M_1/version1_sf_rst_ps7_0_100M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==version1_sf_rst_ps7_0_100M_1 || ORIG_REF_NAME==version1_sf_rst_ps7_0_100M_1}]

# IP: bd/version1_sf/ip/version1_sf_blk_mem_gen_0_0/version1_sf_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==version1_sf_blk_mem_gen_0_0 || ORIG_REF_NAME==version1_sf_blk_mem_gen_0_0}]

# IP: bd/version1_sf/ip/version1_sf_add_generator_0_0/version1_sf_add_generator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==version1_sf_add_generator_0_0 || ORIG_REF_NAME==version1_sf_add_generator_0_0}]

# IP: bd/version1_sf/ip/version1_sf_VGA_SYNC_0_0/version1_sf_VGA_SYNC_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==version1_sf_VGA_SYNC_0_0 || ORIG_REF_NAME==version1_sf_VGA_SYNC_0_0}]

# IP: bd/version1_sf/ip/version1_sf_axi_gpio_0_4/version1_sf_axi_gpio_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==version1_sf_axi_gpio_0_4 || ORIG_REF_NAME==version1_sf_axi_gpio_0_4}]

# IP: bd/version1_sf/ip/version1_sf_xlconstant_0_0/version1_sf_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==version1_sf_xlconstant_0_0 || ORIG_REF_NAME==version1_sf_xlconstant_0_0}]

# IP: bd/version1_sf/ip/version1_sf_ps7_0_axi_periph_1/version1_sf_ps7_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==version1_sf_ps7_0_axi_periph_1 || ORIG_REF_NAME==version1_sf_ps7_0_axi_periph_1}]

# IP: bd/version1_sf/ip/version1_sf_xbar_1/version1_sf_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==version1_sf_xbar_1 || ORIG_REF_NAME==version1_sf_xbar_1}]

# IP: bd/version1_sf/ip/version1_sf_auto_pc_1/version1_sf_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==version1_sf_auto_pc_1 || ORIG_REF_NAME==version1_sf_auto_pc_1}]

# XDC: bd/version1_sf/version1_sf_ooc.xdc
