# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Lab2/zyboVGA_HW.xdc

# Block Designs: bd/version1_hw/version1_hw.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==version1_hw || ORIG_REF_NAME==version1_hw}]

# IP: bd/version1_hw/ip/version1_hw_blk_mem_gen_0_0/version1_hw_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==version1_hw_blk_mem_gen_0_0 || ORIG_REF_NAME==version1_hw_blk_mem_gen_0_0}]

# IP: bd/version1_hw/ip/version1_hw_clk_wiz_0_0/version1_hw_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==version1_hw_clk_wiz_0_0 || ORIG_REF_NAME==version1_hw_clk_wiz_0_0}]

# IP: bd/version1_hw/ip/version1_hw_add_generator_0_0/version1_hw_add_generator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==version1_hw_add_generator_0_0 || ORIG_REF_NAME==version1_hw_add_generator_0_0}]

# IP: bd/version1_hw/ip/version1_hw_control_v1_0_0/version1_hw_control_v1_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==version1_hw_control_v1_0_0 || ORIG_REF_NAME==version1_hw_control_v1_0_0}]

# IP: bd/version1_hw/ip/version1_hw_VGA_SYNC_0_0/version1_hw_VGA_SYNC_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==version1_hw_VGA_SYNC_0_0 || ORIG_REF_NAME==version1_hw_VGA_SYNC_0_0}]

# IP: bd/version1_hw/ip/version1_hw_wr_memory_0_0/version1_hw_wr_memory_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==version1_hw_wr_memory_0_0 || ORIG_REF_NAME==version1_hw_wr_memory_0_0}]

# XDC: bd/version1_hw/version1_hw_ooc.xdc
